---
# handlers file for iac/ansible/roles/docker-compose
- name: executable_permissions
  ansible.builtin.file:
    path: "{{ docker_compose_download_path }}"
    mode: u=rwx,g=rx,o=rx
  register: exec_permis
