---
# tasks file for iac-labs/ansible/roles/golang
  - name: Verify if Golang is installed
    ansible.builtin.stat:
      path: "{{ go_install_path }}/go/bin/go"
    register: go
     
  - name: Install golang "{{ go_version }}"
    notify: update environment
    ansible.builtin.unarchive:
      src: https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz
      dest: "{{ go_install_path }}"
      remote_src: yes
    when: go.stat.exists == False
