---
- name: Verify if new Packages installed
  ansible.builtin.stat:
    path: "{{ docker_new_packages_list }}"
  register: docker_new_packages

- name: Verify root_path
  ansible.builtin.stat:
    path: /root
  register: root_path

- name: Debug stat
  ansible.builtin.debug:
    var: root_path

# - name: Remove docker_new_packages if installed
#   ansible.builtin.apt:
#     name: "{{ docker_new_packages_list }}"
#     state: absent
#   when: docker_new_packages.stat.exists

# - name: Verify if old Packages installed
#   ansible.builtin.stat:
#     path: "{{ docker_packages_list }}"
#   register: docker_packages

# - name: Remove old Docker Packages
#   ansible.builtin.apt:
#     name: "{{ docker_packages_list }}"
#     state: absent
#   when: docker_packages.stat.exists
