---
- include_vars: "vars/{{ ansible_os_family | lower }}/main.yml"
- include_tasks: "tasks/{{ ansible_os_family | lower }}/remove_packages.yml"
- include_tasks: "tasks/{{ ansible_os_family | lower }}/add_repository.yml"
- include_tasks: "tasks/{{ ansible_os_family | lower }}/install_packages.yml"
