---
# PRIVILEG Monday
- name: Go get Dhammer
  shell: "go get -u github.com/ipchama/dhammer"
  args:
    executable: /bin/bash
  environment:
    GOPATH: "{{ go_install_path }}/go/ }}"
  register: gos


- name: debug
  debug:
    msg: "{{ gos }}"

