---
  - include_tasks: "tasks/{{ ansible_os_family | lower }}/remove_packages.yml"
  - include_tasks: "tasks/common/setup_repo.yml"
  - include_tasks: "tasks/{{ ansible_os_family | lower }}/add_packages.yml"
  - include_tasks: "tasks/common/main.yml"
