---
# tasks file for iac/ansible/roles/docker

  - name: Remove old Docker packages
    apt: 
      name: "{{ docker_packages_list }}"
      state: absent
    register: docker_packages

  - name: Setup repository packages
    package:
     name: "{{ docker_packages_list }}"
     state: present
    register: repo_packages

  - name: Add Docker GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg
      id: 7EA0A9C3F273FCD8
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
      state: present
    when: ansible_lsb.id | lower == "ubuntu" or ansible_lsb.id | lower == "debian"
    register: gpg_repo

  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"
      state: present
    when: ansible_lsb.id | lower == "ubuntu" or ansible_lsb.id | lower == "debian"
    register: docker_repo

  - name: Update repository list
    notify: update environment
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_lsb.id | lower == "ubuntu" or ansible_lsb.id | lower == "debian"
    
  - name: Install Docker
    ansible.builtin.package:
     name: "{{ packages }}"
     state: present
    vars:
      packages:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
    register: docker_install
