docker_old_packages_list:
- docker
- docker-client
- docker-client-latest
- docker-common
- docker-latest
- docker-latest-logrotate
- docker-logrotate
- docker-selinux
- docker-engine-linux
- docker-engine

docker_packages_list:
- docker
- docker.io
- containerd
- runc

repo_packages_list:
- dnf-plugins-core
