---
- hosts: ansible_labs
  become: yes
  tasks:

  - name: Update package list
    shell: apt update

  - name: Install Nginx web server
    ansible.builtin.package: 
      name: nginx
      state: absent

  # - name: Copy nginx index page
  #   ansible.builtin.copy:
  #     src: nginx/index.html
  #     dest: /var/www/html/index.html
  #     mode: u=rw-,g=r--,o=r--

  - name: Copy nginx index page
    ansible.builtin.copy:
      src: nginx/ansible.jpg
      dest: /var/www/html/ansible.jpg
      mode: u=rwx,g=r,o=r
  
  # - name: Print all facts
  #   ansible.builtin.debug:
  #    var: nginx_installation
