---
#Inventory host target
- hosts: ansible_labs
  become: yes
  tasks:
  - name:  Update package list
    shell: sudo apt update

  - name: Install Nginx web server
    package:
      name: nginx
      state: present


  - name: Print all facts
      ansible.builtin.debug:
        var: ansible_facts.all_ipv4_addresses[1]

  - name: Copy nginx index page
    copy:
      src: nginx/index.html
      dest: /var/www/html/index.html
      mode: u=rw-,g=r--,o=r--


  - name: Copy Ansible logo.
    copy:
      src: nginx/ansible.jpg
      dest: /var/www/html/ansible.jpg
      mode: u=rwx,g=r,o=r

  - name: Copy mysql config
    copy:
      src: mysql/config
      dest: /tmp/config
