---
name: RoleTests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v2
        with:
          path: devops-hands-on
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          ls -l 
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./devops-hands-on/infra-as-code/labs/ansible/requirements.txt
      - name: Role Test
        run: |
          cd ./devops-hands-on/infra-as-code/labs/ansible
          molecule test
